config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :edit, :show, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :edit,:show,  :create, :update]
  end
  namespace :admin do
    get 'homes/top'
  end
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :public do
    resources :orders, only: [:index, :show, :create, :new]
    post 'orders/info/comfirm/' => 'orders#comfirm'
    get 'orders/info/thanks' => 'orders#thanks'
  end
  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items/dlete/destroy_all' => 'cart_items#destroy_all'
  end
  scope module: :public do
    resource :customers, only: [:show]
    get 'customers/unsubscribe'
    get 'customers/edit/info' => 'customers#edit'
    delete 'customers/destroy' => 'customers#destroy'
    patch 'customers/update/info' => 'customers#update'
  end
  scope module: :public do
    resources :items, only: [:index, :show]

  end
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end



end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :addresses, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_item, dependent: :destroy
  has_many :order_detail, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  
  def with_tax_price
    (price * 1.1).floor
  end
  

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_received_status: { p_wait: 0, p_done: 1, making: 2, s_wait: 3, s_done: 4 },_default: "p_wait"

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum payment_method: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  
  def subtotal
    purchase_price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.all

  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
     @customer=Customer.find(params[:id])
     if @customer.update(customers_params)
       redirect_to customers_path
     end
  end

    private
  def customers_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres=Genre.all
    @genre=Genre.new

  end

  def new
    @genre=Genre.new

  end

  def create
    @genre=Genre.new(genres_params)
    if @genre.save
      redirect_to admin_genres_path
    end

  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
  end

    private
  def genres_params
      params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    if@item.save!
      redirect_to admin_item_path(@item.id), notice: "You have created item successfully."
    else
      @items=Item.all
      render:new, noitce: "An error occurred"
    end
  end

  def show
    @item=Item.find(params[:id])    
  end

  def edit
     @item=Item.find(params[:id])
     @genres=Genre.all
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(params[:id])
    end 
  end
  
    private
  def item_params
      params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    @order=Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id) 
    end
  end


  private
    def order_params
      params.require(:order).permit(:shipping_postal_code, :shipping_address, :shipping_name, :total_payment, :payment_method, :postage, :order_received_status)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   def after_sign_in_path_for(resource)
     if resource == :admin
        admin_session_path
     end 
   end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
   if resource == :admin
      admin_session_path
   elsif resource == :public
      root_path
   end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class=" ">
      <div class="">
        <h2 class="bg-light text-center col-7 ">
          <%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細
        </h2>
        <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
          <table class="table table-borderless mt-3">
            <thead>
              <tr>
                <th class="col-3">
                  会員ID
                </th>
               <td>
                  <%= @customer.id %>
                </td>
              </tr>
              <tr>
                <th>
                  氏名
                </th>
                <td>
                  <%= f.text_field :first_name %> 
                </td>
                <td>
                  <%= f.text_field :last_name %>
                </td>
              </tr>
              <tr>
                <th>
                  フリガナ
                </th>
                <td>
                  <%= f.text_field :first_name_kana %>
                </td>
                <td>
                  <%= f.text_field :last_name_kana %>
                </td>
              </tr>
              <tr>
                <th>
                  郵便番号
                </th>
                <td>
                  <%= f.text_field :postal_code %>
                </td>
              </tr>
              <tr>
                <th>
                  住所
                </th>
                <td>
                  <%= f.text_field :address %>
                </td>
              </tr>
              <tr>
                <th>
                  電話番号
                </th>
                <td>
                  <%= f.text_field :telephone_number %>
                </td>
              </tr>
              <tr>
                <th>
                  メールアドレス
                </th>
                <td>
                  <%= f.text_field :email %>
                </td>
              </tr>
              <tr>
                <th>
                  会員ステータス
                </th>
                <td>
                     <%= f.radio_button :is_deleted, :false %>有効
                     <%= f.radio_button :is_deleted, :true %>退会
                </td>
              </tr>
              <tr>
                <th class="colspan-3">
                </th>
                <td class="col-3">
                    <%= f.submit "更新",class: 'btn btn-success' %>
                </td>
              </tr>
            </thead>
          </table>
        <% end %>
      </div>
    </div>
  </div

app/views/admin/customers/index.html.erb
<%= render "admin/shared/links" %>  
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2 class="bg-light col-3 text-center mt-5">会員一覧</h2>
        <table class="table table-hover table-inverse mt-5 mx-5">
          <thead>
            <tr class="bg-light">
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td>
                  <%= customer.id %>
                </td>
                <td><%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.first_name %>　<%= customer.last_name %>
                  <% end %>
                </td>
                <td>
                  <%= customer.email %>
                </td>
                <td>
                  <% if customer.is_deleted == false %>
                    <p class="text-success">
                      有効
                    </p>
                  <% else %>
                    <p class="text-secondary">
                      退会
                    </p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-8 offset-md-1">
        <h2 class="bg-light text-center col-7 ">
          <%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細
        </h2>
        <table class="table table-borderless mt-3">
          <thead>
            <tr>
              <th class="col-3">
                会員ID
              </th>
             <td>
                <%= @customer.id %>
              </td>
            </tr>
            <tr>
              <th>
                氏名
              </th>
              <td>
                <%= @customer.first_name %> <%= @customer.last_name %>
              </td>
            </tr>
            <tr>
              <th>
                フリガナ
              </th>
              <td>
                <%= @customer.first_name_kana %> <%= @customer.last_name_kana %>
              </td>
            </tr>
            <tr>
              <th>
                郵便番号
              </th>
              <td>
                <%= @customer.postal_code %>
              </td>
            </tr>
            <tr>
              <th>
                住所
              </th>
              <td>
                <%= @customer.address %>
              </td>
            </tr>
            <tr>
              <th>
                電話番号
              </th>
              <td>
                <%= @customer.telephone_number %>
              </td>
            </tr>
            <tr>
              <th>
                メールアドレス
              </th>
              <td>
                <%= @customer.email %>
              </td>
            </tr>
            <tr>
              <th>
                会員ステータス
              </th>
              <td>
                <% if @customer.is_deleted == false %>
                  <p class="text-success pt-auto">
                    有効
                  </p>
                <% else %>
                  <p class="text-secondary ">
                    退会
                  </p>
                <% end %>
              </td>
            </tr>
            <tr>
              <th class="colspan-3">
              </th>
              <td class="col-3">
                <%= link_to "編集する",  edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
              </td>
              <td>
                 <%= link_to "注文履歴一覧を見る", admin_homes_top_path, class: "btn btn-info" %>
              </td>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>