config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :edit, :show, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :edit,:show,  :create, :update]
  end
  namespace :admin do
    get 'homes/top'
  end
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :public do
    resources :orders, only: [:index, :show, :create, :new]
    post 'orders/info/comfirm/' => 'orders#comfirm'
    get 'orders/info/thanks' => 'orders#thanks'
  end
  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items/dlete/destroy_all' => 'cart_items#destroy_all'
  end
  scope module: :public do
    resource :customers, only: [:show]
    get 'customers/unsubscribe'
    get 'customers/edit/info' => 'customers#edit'
    delete 'customers/destroy' => 'customers#destroy'
    patch 'customers/update/info' => 'customers#update'
  end
  scope module: :public do
    resources :items, only: [:index, :show]

  end
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end



end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :addresses, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_item, dependent: :destroy
  has_many :order_detail, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  
  def with_tax_price
    (price * 1.1).floor
  end
  

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_received_status: { p_wait: 0, p_done: 1, making: 2, s_wait: 3, s_done: 4 },_default: "p_wait"

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum payment_method: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  
  def subtotal
    purchase_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres=Genre.all
    @genre=Genre.new

  end

  def new
    @genre=Genre.new

  end

  def create
    @genre=Genre.new(genres_params)
    if @genre.save
      redirect_to admin_genres_path
    end

  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
  end

    private
  def genres_params
      params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    if@item.save!
      redirect_to admin_item_path(@item.id), notice: "You have created item successfully."
    else
      @items=Item.all
      render:new, noitce: "An error occurred"
    end
  end

  def show
    @item=Item.find(params[:id])    
  end

  def edit
     @item=Item.find(params[:id])
     @genres=Genre.all
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(params[:id])
    end 
  end
  
    private
  def item_params
      params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end

  def update
    @order=Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id) 
    end
  end


  private
    def order_params
      params.require(:order).permit(:shipping_postal_code, :shipping_address, :shipping_name, :total_payment, :payment_method, :postage, :order_received_status)
    end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
    def after_sign_in_path_for(resource)
      admin_homes_top_path
    end
    
    
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   def after_sign_in_path_for(resource)
     if resource == :admin
        admin_session_path
     end 
   end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
   if resource == :admin
      admin_session_path
   elsif resource == :public
      root_path
   end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="mt-5">
        <h1>ジャンル編集</h1>
        <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <div class="row mt-5">
          <div class="mx-5">
            <h6 class="text-center">
              <strong>
                ジャンル名
              </strong>
            </h6>
          </div class="mx-5">
          <%= f.text_field :name %>
          <div class="mx-5">
            <%= f.submit "Update",class: 'btn btn-success' %>
          </div>
          <% end %>
        </div>
    </div>
  </div>

app/views/admin/genres/index.html.erb
<%= render "admin/shared/links" %>  
  <div class="container px-5 px-sm-0">
    <div class="row mt-3">
      <div class="col-md-8 offset-md-1">
        <h2 class="bg-light col-md-6 text-center">ジャンル一覧・追加</h2>
            <div class="mt-5 ">
              <%= form_with model: @genre, url: admin_genres_path do |f| %>
                <h4>ジャンル名</h4>
                <%= f.text_field :name %>
                <%= f.submit '新規ジャンル投稿',class: 'btn btn-success' %>
             <% end %>
        <div class="col-5">   
          <table class="table table-hover table-inverse mt-5">
            <thead>
              <tr class="bg-light">
                <th>ジャンル</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @genres.each do |genre| %>
                <tr>
                  <td>
                    <%= genre.name %>
                  </td>
                  <td><%= link_to edit_admin_genre_path(genre.id) do %>
                        <div class="btn btn-success">編集する</div>
                      <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
           </table>
         </div> 
      </div>
    </div>
  </div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="column">
      <h2 class="bg-light mt-3 col-3 text-center">商品編集</h2>
        <div class="row">
          <div class="mx-auto col-11 col-sm-15 col-lg-8 col-xl-6">
             <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品画像 %>
                 </div>
                 <div class="px-3 pt-3">
                   <%= f.file_field :image, accept: "image/*" %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品名　 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.text_field :name %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品説明 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.text_area :introduction %>
                 </div>
               </div>
               <!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->
               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :ジャンル  %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :税抜価格 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.number_field :price %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :販売ステータス %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.radio_button :is_active, :true %>販売中
                   <%= f.radio_button :is_active, :false %>販売停止中
                 </div>
               </div>

               <div class="mt-3 ">
                 <%= f.submit '変更を保存',class: 'btn btn-success' %>
               </div>
              <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/items/index.html.erb
<%= render "admin/shared/links" %>
<p><%= notice %></p>
  <div class="container px-sm-0">
      <div class="row">
        <div class="col-md-8 offset-md-1">
          <h2 class="mt-5 bg-light col-3 align-center">商品一覧</h2>
          <table class="table table-hover table-inverse mt-5 ">
            <thead>
              <tr>
                <th class="bg-light">商品ID</th>
                <th class="bg-light">商品名</th>
                <th class="bg-light">商品説明</th>
                <th class="bg-light">税抜価格</th>
                <th class="bg-light">ジャンル</th>
                <th class="bg-light">販売ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td>
                    <%= item.id %>
                  </td>
                  <td>
                    <%= link_to admin_item_path(item.id) do %>
                      <%= item.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= item.introduction %>
                  </td>
                  <td>
                    <%= item.price %>
                  </td>
                  <td>
                    <%= item.genre.name %>
                  </td>
                 <td>
                   <% if item.is_active==true %>
                     <p class="text-success">販売中</p>
                   <% else %>
                     <P class="text-secondary">販売停止中</P>
                   <% end %>
                 </td>
                </tr>
              <% end %>
              <%= paginate @items %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="text-center">
        <%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
      </div>
    </div>

app/views/admin/items/new.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="column">
      <h2 class="bg-light mt-3 col-3">新規商品登録</h2>
        <div class="row">
          <div class="mx-auto col-11 col-sm-15 col-lg-8 col-xl-6">
             <%= form_with model: @item, url: admin_items_path do |f| %>
               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品画像 %>
                 </div>
                 <div class="px-3 pt-3">
                   <%= f.file_field :image, accept: "image/*" %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品名　 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.text_field :name %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :商品説明 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.text_area :introduction %>
                 </div>
               </div>
               <!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->
               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :ジャンル  %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :税抜価格 %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.number_field :price %>
                 </div>
               </div>

               <div class="field row">
                 <div class="px-3 pt-3">
                   <%= f.label :販売ステータス %>
                 </div>
                 <div class="px-3 pt-3 ">
                   <%= f.radio_button :is_active, :true %>販売中
                   <%= f.radio_button :is_active, :false %>販売停止中
                 </div>
               </div>

               <div class="mt-3 ">
                 <%= f.submit '新規登録',class: 'btn btn-success' %>
               </div>
              <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/items/show.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="column">
      <div class="col-md-8 offset-md-1">
        <h2>商品詳細</h2>
          <div class="row">
            <div>
              <% if @item.image.attached? %>
                <%= image_tag @item.image %>
              <% else %>
                <%= image_tag 'no_image', size: "100x100" %>
              <% end %>
            </div>
            <div>
              <div class="mx-3 field row">
               <div class="px-3 pt-3">
                 商品説明
               </div>
               <div class="px-3 pt-3">
                 <%= @item.name %>
               </div>
              </div>

              <div class="mx-3 field row">
               <div class="px-3 pt-3">
                 商品説明
               </div>
               <div class="px-3 pt-3">
                 <%= @item.introduction %>
               </div>
              </div>

              <div class="mx-3 field row">
               <div class="px-3 pt-3">
                 ジャンル
               </div>
               <div class="px-3 pt-3">
                 <%= @item.genre.name %>
               </div>
              </div>

              <div class="mx-3 field row">
               <div class="px-3 pt-3">
                 税込価格<br>
                 (税抜価格)
               </div>
               <div class="px-3 pt-3">
                  ¥<%= @item.price / 10 + @item.price %>
                  (<%=  @item.price %>)円
               </div>
              </div>

              <div class="mx-3 field row">
               <div class="px-3 pt-3">
                 販売ステータス
               </div>
               <div class="px-3 pt-3">
                 <% if @item.is_active==true %>
                   <p class="text-success">販売中</p>
                 <% else %>
                   <P class="text-secondary">販売停止中</P>
                 <% end %>
               </div>
              </div>
            </div>
          </div>
      </div>
      <div class="text-center">
        <button class="btn btn-success">
          <%= link_to edit_admin_item_path(@item.id) do %>
            編集する
          <% end %>
        </button>
      </div>
    </div>
  </div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<%= render "admin/shared/links" %>
  <div class="container">
    <div class="mt-5">
      <h2 class="bg-light text-center col-4 mx-5">
        注文履歴詳細
      </h2>
      <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th class="col-2">
                購入者
              </th>
              <td>
                <%= link_to admin_customer_path( @order.customer.id) do %>
                  <%= @order.shipping_name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>
                注文日
              </th>
              <td>
                <%= @order.created_at.strftime('%Y/%m/%d') %>
              </td>
            </tr>
            <tr>
              <th>
                配送先
              </th>
              <td>
                〒<%= @order.shipping_postal_code %>
                <%= @order.shipping_address %><br>
                <%= @order.shipping_name %>
              </td>
            </tr>
            <tr>
              <th>
                支払方法
              </th>
              <td>
                <%= @order.payment_method_i18n %>
              </td>
            </tr>
            <tr>
              <th>
                注文ステータス
              </th>
              <td>
                <%= f.select :order_received_status, [['入金待ち','p_wait'],['入金確認','p_done'],['製作中','making'],['発送準備中','s_wait'],['発送済み','s_done']] %>
                <%= f.submit "更新", class: "btn btn-success" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
      <div class="row">
        <div class="col-8">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>
                  商品名
                </th>
                <th>
                  単価(税込)
                </th>
                <th>
                  数量
                </th>
                <th>
                  小計
                </th>
              </tr>
            </thead>
            <% @order_details.each do |order_detail| %>
              <tbody>
                <tr>
                  <td>
                    <%= order_detail.item.name %>
                  </td>
                  <td>
                    <%= order_detail.purchase_price %>
                  </td>
                  <td>
                    <%= order_detail.amount %>
                  </td>
                  <td>
                    <%= order_detail.subtotal %>
                  </td>
                </tr>
            </tbody>
            <% end %>
          </table>
        </div>
        <div class="d-flex align-items-end">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th>
                  商品合計
                </th>
                <td>
                  <%= @order.total_payment %>円
                </td>
              </tr>
              <tr>
                <th>
                  送料
                </th>
                <td>
                  <%= @order.postage %>円
                </td>
              </tr>
              <tr>
                <th>
                  請求金額合計
                </th>
                <td>
                  <strong><%= @order.total_payment + @order.postage %>円</strong>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>