config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :edit, :show, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :edit, :create, :update]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :edit,:show,  :create, :update]
  end
  namespace :admin do
    get 'homes/top'
  end
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :public do
    resources :orders, only: [:index, :show, :create, :new]
    post 'orders/info/comfirm/' => 'orders#comfirm'
    get 'orders/info/thanks' => 'orders#thanks'
  end
  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items/dlete/destroy_all' => 'cart_items#destroy_all'
  end
  scope module: :public do
    resource :customers, only: [:show]
    get 'customers/unsubscribe'
    get 'customers/edit/info' => 'customers#edit'
    delete 'customers/destroy' => 'customers#destroy'
    patch 'customers/update/info' => 'customers#update'
  end
  scope module: :public do
    resources :items, only: [:index, :show]

  end
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end



end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :addresses, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_item, dependent: :destroy
  has_many :order_detail, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  
  def with_tax_price
    (price * 1.1).floor
  end
  

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_received_status: { p_wait: 0, p_done: 1, making: 2, s_wait: 3, s_done: 4 },_default: "p_wait"

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum payment_method: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  
  def subtotal
    purchase_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres=Genre.all
    @genre=Genre.new

  end

  def new
    @genre=Genre.new

  end

  def create
    @genre=Genre.new(genres_params)
    if @genre.save
      redirect_to admin_genres_path
    end

  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
  end

    private
  def genres_params
      params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    if@item.save!
      redirect_to admin_item_path(@item.id), notice: "You have created item successfully."
    else
      @items=Item.all
      render:new, noitce: "An error occurred"
    end
  end

  def show
    @item=Item.find(params[:id])    
  end

  def edit
     @item=Item.find(params[:id])
     @genres=Genre.all
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(params[:id])
    end 
  end
  
    private
  def item_params
      params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   def after_sign_in_path_for(resource)
     if resource == :admin
        admin_session_path
     end 
   end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
   if resource == :admin
      admin_session_path
   elsif resource == :public
      root_path
   end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="https://090ddf88141c4033a1a0954dcce7f49e.vfs.cloud9.ap-northeast-1.amazonaws.com/">
   <%= image_tag 'top_cake.jpg', size: '100x50' %>
  </a>


    <button class="navbar-toggler" type="button" date-toggle="collapse" data-target="#navbarNavDropdown"
    aria-label="Toggle navigation" aria-expanded="false">
     <span class="navbar-toggle-icon"></span>
    </button>
    <div class="collaspe navbar-collaspe" id="navbarNavDropdown"></div>
     <ul class="navbar-nav ml-auto">
       <li>
        <div class="nav-link text-light">
         <% if admin_signed_in? %>
          <%= link_to "商品一覧", admin_items_path %>
         <% else %>
           <%= link_to "About", homes_about_path %>
         <% end %>
        </div>
        <li>
        <div class="nav-link text-light">
         <% if admin_signed_in? %>
            <%= link_to "会員一覧", admin_customers_path %>
         <% else %>
           <%= link_to "商品一覧", admin_items_path %>
         <% end %>
        </div>
       </li>
       <li>
        <div class="nav-link text-light">
         <% if admin_signed_in? %>
           <%= link_to "注文履歴一覧", admin_homes_top_path %>
         <% else %>
           <%= link_to "新規登録", new_admin_session_path %>
         <% end %>
        </div>
       </li>
       <li>
         <div class="nav-link text-light">
          <% if admin_signed_in? %>
            <%= link_to "ジャンル一覧", admin_genres_path %>
          <% else %>
            <%= link_to "ログイン", admin_session_path %>
          <% end %>
        </div>
       <li>
         <div class="nav-link text-light">
          <% if admin_signed_in? %>
           <%= link_to "ログアウト", destroy_admin_session_path, method: :delete  %>
          <% end %>
        </div>
       </li>

     </ul>
  </div>
  </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOcake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <main>

     <%= yield %>
  </main>
  </body>
</html>